### PR TITLE
Remove logic handling preprocessor macros

### PR DESCRIPTION
**Pull request by Wilfred**
TypeScript does not have preprocessor macros. It was proposed in https://github.com/Microsoft/TypeScript/issues/4691 but never added to the language.

### CODE REVIEW

**Comment by josteink** [comment]
Thanks for another PR @Wilfred!

I'm all for removing pointless legacy code to keep the rest of the code easier to maintain.

Glancing over this, I cannot see it covered by any tests, and all the code in question seems to stem from the initial commit (meaning none of the current maintainers feel any ownership to it).

As long as everything still works, I'm supportive of these changes. Anyone else have any opinions?

**Comment by josteink** [comment]
LGTM. I've just ran and tested this on some of my projects, and I can't see it introducing any regressions.

Consider it merged!

**Comment by quirinpa** [comment]
Oh my, what destructive joy. I joke. You know what this would be useful for?
Conditional static imports. Oh well. Good thing we can still run gcc before tsc, or.. Use gcc for dependency resolution, even..

Turtle master, into the sky, on a cloud.

**Comment by quirinpa** [comment]
Oh oh. I forgot to say: Conditional static imports. Just joking.

Remember what you have destroyed.

I'll just stop now.

**Comment by josteink** [comment]
Maybe this is a joke, and I'm just slow (it's monday morning after all)...

But would you care to elaborate on this with an example? 😄

**Comment by quirinpa** [comment]
You're not slow, I'm just confusing, and confused. All the time.

Here it goes;

In a config.h file (or though gcc's -D flag):
```c
#define DEVELOPMENT 1
```
And then...
```js+c
#if DEVELOPMENT
import { a } from 'whatever-dev';
#else
import { a } from 'whatever-prod';
#endif
```
It could be used for many other things as well, of course.
Kawabunga.

**Comment by quirinpa** [comment]
I'm not sure if that should be typescript's responsibility...

But it would be a shame to have to let go of [Tsuquyomi](https://github.com/Quramy/tsuquyomi) in order to use the gcc preprocessor.

I wish JS build tools integrated well with oldschool tools... I assume it is hard to do single-file compilation efficiently in JS...

Dead turtle.

**Comment by Wilfred** [comment]
This PR did not actually change typescript, it only changed syntax highlighting in Emacs.

**Pull request merged**
